version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./env/.env
    # volumes:
    #   - .:/usr/src/app
    # command: go run cmd/main.go -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:15.1
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./env/db.env
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
